api: {
  key: ${?API_KEY}
}

server {
  host: "0.0.0.0"
  host: ${?HOST}
  port: 7070
  port: ${?PORT}
}

clients {
  alpha-vantage {
    base-uri: "https://www.alphavantage.co"
    api-key: "api-key"
    api-key: ${?ALPHA_VANTAGE_API_KEY}
  }
  finnhub {
    base-uri: "https://finnhub.io"
    api-key: "api-key"
    api-key: ${?FINNHUB_API_KEY}
  }
  twelve-data {
    base-uri: "https://api.twelvedata.com"
    api-key: "api-key"
    api-key: ${?TWELVE_DATA_API_KEY}
  }
}

action-executor {
  concurrency: 16
  concurrency: ${?ACTION_EXECUTOR_CONCURRENCY}
}

mongo {
  user: ${MONGO_USER}
  password: ${MONGO_PASSWORD}
  host: ${MONGO_HOST}
  db-name: "stocks-checker"
}