api: {
  key: "api-key"
  key: ${?API_KEY}
}

server {
  host: "0.0.0.0"
  host: ${?HOST}
  port: 7070
  port: ${?PORT}
}

clients {
  financial-modeling-prep {
    base-uri: "https://financialmodelingprep.com"
    api-key: "api-key"
    api-key: ${?FINANCIAL_MODELING_PREP_API_KEY}
  }
  alpha-vantage {
    base-uri: "https://www.alphavantage.co"
    api-key: "api-key"
    api-key: ${?ALPHA_VANTAGE_API_KEY}
  }
  finnhub {
    base-uri: "https://finnhub.io"
    api-key: "api-key"
    api-key: ${?FINNHUB_API_KEY}
  }
}

mongo {
  connection-uri: "mongodb+srv://"${?MONGO_USER}":"${?MONGO_PASSWORD}"@"${?MONGO_HOST}"/stocks-checker"
  db-name: "stocks-checker"
}